<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PatientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('patients')->insert([
            [
                'first_name'     => 'Mark',
                'last_name'      => 'Lopez',
                'image_filename' => null,
                'date_of_birth'  => '1992-04-12',
                'sex'            => 'Male',
                'address'        => 'Bacolod City, Negros Occidental',
                'occupation'     => 'Driver',
                'contact_no'     => '09170000001',
                'marital_status' => 'Single',
                'guardian_name'  => "Linda Lopez",
                'created_at'     => now(),
                'updated_at'     => now(),                
            ],
            [
                'first_name'     => 'Angela',
                'last_name'      => 'Garcia',
                'image_filename' => 'profile-patient-2.jpg',
                'date_of_birth'  => '1988-07-25',
                'sex'            => 'Female',
                'address'        => 'Bacolod City, Negros Occidental',
                'occupation'     => 'Nurse',
                'contact_no'     => '09170000002',
                'marital_status' => 'Married',
                'guardian_name'  => null,
                'created_at'     => now(),
                'updated_at'     => now(),                
            ],
            [
                'first_name'     => 'Carlo',
                'last_name'      => 'Fernandez',
                'image_filename' => 'profile-patient-3.jpg',
                'date_of_birth'  => '2014-02-18',
                'sex'            => 'Male',
                'address'        => 'Bacolod City, Negros Occidental',
                'occupation'     => 'Student',
                'contact_no'     => '09170000003',
                'marital_status' => 'Single',
                'guardian_name'  => 'Liza Fernandez',
                'created_at'     => now(),
                'updated_at'     => now(),                
            ],
            [
                'first_name'     => 'Liza',
                'last_name'      => 'Torres',
                'image_filename' => 'profile-patient-4.jpg',
                'date_of_birth'  => '1995-11-03',
                'sex'            => 'Female',
                'address'        => 'Bacolod City, Negros Occidental',
                'occupation'     => 'Teacher',
                'contact_no'     => '09170000004',
                'marital_status' => 'Single',
                'guardian_name'  => null,
                'created_at'     => now(),
                'updated_at'     => now(),                
            ],
            [
                'first_name'     => 'Ramon',
                'last_name'      => 'Diaz',
                'image_filename' => 'profile-patient-5.jpg',
                'date_of_birth'  => '1980-09-14',
                'sex'            => 'Male',
                'address'        => 'Bacolod City, Negros Occidental',
                'occupation'     => 'Mechanic',
                'contact_no'     => '09170000005',
                'marital_status' => 'Married',
                'guardian_name'  => null,
                'created_at'     => now(),
                'updated_at'     => now(),                
            ],
            [
                'first_name'     => 'Jessa',
                'last_name'      => 'Villanueva',
                'image_filename' => null,
                'date_of_birth'  => '2000-05-20',
                'sex'            => 'Female',
                'address'        => 'Bacolod City, Negros Occidental',
                'occupation'     => 'Student',
                'contact_no'     => '09170000006',
                'marital_status' => 'Single',
                'guardian_name'  => "Sophia Villanueva",
                'created_at'     => now(),
                'updated_at'     => now(),                
            ],
            [
                'first_name'     => 'Paul',
                'last_name'      => 'Rivera',
                'image_filename' => 'profile-patient-7.jpg',
                'date_of_birth'  => '1993-01-08',
                'sex'            => 'Male',
                'address'        => 'Bacolod City, Negros Occidental',
                'occupation'     => 'Engineer',
                'contact_no'     => '09170000007',
                'marital_status' => 'Single',
                'guardian_name'  => null,
                'created_at'     => now(),
                'updated_at'     => now(),                
            ],
            [
                'first_name'     => 'Kim',
                'last_name'      => 'Morales',
                'image_filename' => 'profile-patient-8.jpg',
                'date_of_birth'  => '1997-12-11',
                'sex'            => 'Female',
                'address'        => 'Bacolod City, Negros Occidental',
                'occupation'     => 'Cashier',
                'contact_no'     => '09170000008',
                'marital_status' => 'Single',
                'guardian_name'  => null,
                'created_at'     => now(),
                'updated_at'     => now(),                
            ],
            [
                'first_name'     => 'Leo',
                'last_name'      => 'Castro',
                'image_filename' => 'profile-patient-9.jpg',
                'date_of_birth'  => '1986-06-02',
                'sex'            => 'Male',
                'address'        => 'Bacolod City, Negros Occidental',
                'occupation'     => 'Police Officer',
                'contact_no'     => '09170000009',
                'marital_status' => 'Married',
                'guardian_name'  => "Sam Castro",
                'created_at'     => now(),
                'updated_at'     => now(),                
            ],
            [
                'first_name'     => 'Anna',
                'last_name'      => 'Ramos',
                'image_filename' => null,
                'date_of_birth'  => '1991-03-27',
                'sex'            => 'Female',
                'address'        => 'Bacolod City, Negros Occidental',
                'occupation'     => 'HR Staff',
                'contact_no'     => '09170000010',
                'marital_status' => 'Single',
                'guardian_name'  => null,
                'created_at'     => now(),
                'updated_at'     => now(),                
            ],
            [
                'first_name'     => 'Bryan',
                'last_name'      => 'Flores',
                'image_filename' => null,
                'date_of_birth'  => '1994-10-10',
                'sex'            => 'Male',
                'address'        => 'Bacolod City, Negros Occidental',
                'occupation'     => 'Security Guard',
                'contact_no'     => '09170000011',
                'marital_status' => 'Single',
                'guardian_name'  => null,
                'created_at'     => now(),
                'updated_at'     => now(),                
            ],
            [
                'first_name'     => 'Ella',
                'last_name'      => 'Gutierrez',
                'image_filename' => 'profile-patient-12.jpg',
                'date_of_birth'  => '1989-08-08',
                'sex'            => 'Female',
                'address'        => 'Bacolod City, Negros Occidental',
                'occupation'     => 'Accountant',
                'contact_no'     => '09170000012',
                'marital_status' => 'Married',
                'guardian_name'  => null,
                'created_at'     => now(),
                'updated_at'     => now(),                
            ],
            [
                'first_name'     => 'Noel',
                'last_name'      => 'Sanchez',
                'image_filename' => 'profile-patient-13.jpg',
                'date_of_birth'  => '1975-02-14',
                'sex'            => 'Male',
                'address'        => 'Bacolod City, Negros Occidental',
                'occupation'     => 'Farmer',
                'contact_no'     => '09170000013',
                'marital_status' => 'Married',
                'guardian_name'  => null,
                'created_at'     => now(),
                'updated_at'     => now(),                
            ],
            [
                'first_name'     => 'Joy',
                'last_name'      => 'Cruz',
                'image_filename' => null,
                'date_of_birth'  => '2002-01-19',
                'sex'            => 'Female',
                'address'        => 'Bacolod City, Negros Occidental',
                'occupation'     => 'Student',
                'contact_no'     => '09170000014',
                'marital_status' => 'Single',
                'guardian_name'  => null,
                'created_at'     => now(),
                'updated_at'     => now(),                
            ],
            [
                'first_name'     => 'Arvin',
                'last_name'      => 'Navarro',
                'image_filename' => 'profile-patient-15.jpg',
                'date_of_birth'  => '1990-05-05',
                'sex'            => 'Male',
                'address'        => 'Bacolod City, Negros Occidental',
                'occupation'     => 'Chef',
                'contact_no'     => '09170000015',
                'marital_status' => 'Married',
                'guardian_name'  => null,
                'created_at'     => now(),
                'updated_at'     => now(),                
            ],
            [
                'first_name'     => 'Diane',
                'last_name'      => 'Mendoza',
                'image_filename' => 'profile-patient-16.jpg',
                'date_of_birth'  => '1996-09-09',
                'sex'            => 'Female',
                'address'        => 'Bacolod City, Negros Occidental',
                'occupation'     => 'Sales Clerk',
                'contact_no'     => '09170000016',
                'marital_status' => 'Single',
                'guardian_name'  => null,
                'created_at'     => now(),
                'updated_at'     => now(),                
            ],
            [
                'first_name'     => 'Kevin',
                'last_name'      => 'Aquino',
                'image_filename' => 'profile-patient-17.jpg',
                'date_of_birth'  => '1987-03-03',
                'sex'            => 'Male',
                'address'        => 'Bacolod City, Negros Occidental',
                'occupation'     => 'IT Support',
                'contact_no'     => '09170000017',
                'marital_status' => 'Single',
                'guardian_name'  => null,
                'created_at'     => now(),
                'updated_at'     => now(),                
            ],
            [
                'first_name'     => 'Faith',
                'last_name'      => 'Salazar',
                'image_filename' => 'profile-patient-18.jpg',
                'date_of_birth'  => '1998-07-07',
                'sex'            => 'Female',
                'address'        => 'Bacolod City, Negros Occidental',
                'occupation'     => 'Receptionist',
                'contact_no'     => '09170000018',
                'marital_status' => 'Single',
                'guardian_name'  => null,
                'created_at'     => now(),
                'updated_at'     => now(),                
            ],
            [
                'first_name'     => 'Oscar',
                'last_name'      => 'Pineda',
                'image_filename' => null,
                'date_of_birth'  => '1979-11-11',
                'sex'            => 'Male',
                'address'        => 'Bacolod City, Negros Occidental',
                'occupation'     => 'Driver',
                'contact_no'     => '09170000019',
                'marital_status' => 'Married',
                'guardian_name'  => null,
                'created_at'     => now(),
                'updated_at'     => now(),                
            ],
            [
                'first_name'     => 'Rose',
                'last_name'      => 'Bautista',
                'image_filename' => 'profile-patient-20.jpg',
                'date_of_birth'  => '1993-12-12',
                'sex'            => 'Female',
                'address'        => 'Bacolod City, Negros Occidental',
                'occupation'     => 'Teacher',
                'contact_no'     => '09170000020',
                'marital_status' => 'Single',
                'guardian_name'  => null,
                'created_at'     => now(),
                'updated_at'     => now(),                
            ],
        ]);
        
    }
}
